[2025-08-11T02:20:32.022+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: public_health_data_pipeline.stage_raw_data_to_s3 manual__2025-08-11T02:20:30.355885+00:00 [queued]>
[2025-08-11T02:20:32.028+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: public_health_data_pipeline.stage_raw_data_to_s3 manual__2025-08-11T02:20:30.355885+00:00 [queued]>
[2025-08-11T02:20:32.029+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-11T02:20:32.035+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): stage_raw_data_to_s3> on 2025-08-11 02:20:30.355885+00:00
[2025-08-11T02:20:32.037+0000] {standard_task_runner.py:60} INFO - Started process 181 to run task
[2025-08-11T02:20:32.038+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'public_health_data_pipeline', 'stage_raw_data_to_s3', 'manual__2025-08-11T02:20:30.355885+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/covid_data_pipeline.py', '--cfg-path', '/tmp/tmp86id9xu7']
[2025-08-11T02:20:32.039+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask stage_raw_data_to_s3
[2025-08-11T02:20:32.057+0000] {task_command.py:423} INFO - Running <TaskInstance: public_health_data_pipeline.stage_raw_data_to_s3 manual__2025-08-11T02:20:30.355885+00:00 [running]> on host 88fedbca0f53
[2025-08-11T02:20:32.155+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='public_health_data_pipeline' AIRFLOW_CTX_TASK_ID='stage_raw_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-08-11T02:20:30.355885+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-11T02:20:30.355885+00:00'
[2025-08-11T02:20:32.161+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-11T02:20:32.288+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-08-11T02:20:33.016+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-11T02:20:33.024+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=public_health_data_pipeline, task_id=stage_raw_data_to_s3, execution_date=20250811T022030, start_date=20250811T022032, end_date=20250811T022033
[2025-08-11T02:20:33.064+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-11T02:20:33.075+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
