[2025-08-11T20:54:40.402+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: public_health_data_pipeline.create_postgres_table_if_not_exists manual__2025-08-11T20:54:39.175283+00:00 [queued]>
[2025-08-11T20:54:40.406+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: public_health_data_pipeline.create_postgres_table_if_not_exists manual__2025-08-11T20:54:39.175283+00:00 [queued]>
[2025-08-11T20:54:40.407+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-11T20:54:40.413+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): create_postgres_table_if_not_exists> on 2025-08-11 20:54:39.175283+00:00
[2025-08-11T20:54:40.416+0000] {standard_task_runner.py:60} INFO - Started process 175 to run task
[2025-08-11T20:54:40.418+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'public_health_data_pipeline', 'create_postgres_table_if_not_exists', 'manual__2025-08-11T20:54:39.175283+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/covid_data_pipeline.py', '--cfg-path', '/tmp/tmpul1l0gsw']
[2025-08-11T20:54:40.419+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask create_postgres_table_if_not_exists
[2025-08-11T20:54:40.427+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-11T20:54:40.444+0000] {task_command.py:423} INFO - Running <TaskInstance: public_health_data_pipeline.create_postgres_table_if_not_exists manual__2025-08-11T20:54:39.175283+00:00 [running]> on host ebb21e81efa5
[2025-08-11T20:54:40.491+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='public_health_data_pipeline' AIRFLOW_CTX_TASK_ID='create_postgres_table_if_not_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-08-11T20:54:39.175283+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-11T20:54:39.175283+00:00'
[2025-08-11T20:54:40.496+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-08-11T20:54:40.498+0000] {sql.py:450} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS covid_state_metrics (
                date DATE,
                state VARCHAR(50),
                fips INTEGER,
                cases INTEGER,
                deaths INTEGER,
                new_cases INTEGER,
                new_deaths INTEGER,
                PRIMARY KEY (date, state)
            );
        , parameters: None
[2025-08-11T20:54:40.499+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-11T20:54:40.503+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=public_health_data_pipeline, task_id=create_postgres_table_if_not_exists, execution_date=20250811T205439, start_date=20250811T205440, end_date=20250811T205440
[2025-08-11T20:54:40.514+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-11T20:54:40.531+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
