[2025-08-11T02:18:29.639+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: public_health_data_pipeline.stage_raw_data_to_s3 manual__2025-08-11T02:18:28.046433+00:00 [queued]>
[2025-08-11T02:18:29.643+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: public_health_data_pipeline.stage_raw_data_to_s3 manual__2025-08-11T02:18:28.046433+00:00 [queued]>
[2025-08-11T02:18:29.644+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-11T02:18:29.649+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): stage_raw_data_to_s3> on 2025-08-11 02:18:28.046433+00:00
[2025-08-11T02:18:29.651+0000] {standard_task_runner.py:60} INFO - Started process 181 to run task
[2025-08-11T02:18:29.652+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'public_health_data_pipeline', 'stage_raw_data_to_s3', 'manual__2025-08-11T02:18:28.046433+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/covid_data_pipeline.py', '--cfg-path', '/tmp/tmpccypwxpx']
[2025-08-11T02:18:29.653+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask stage_raw_data_to_s3
[2025-08-11T02:18:29.673+0000] {task_command.py:423} INFO - Running <TaskInstance: public_health_data_pipeline.stage_raw_data_to_s3 manual__2025-08-11T02:18:28.046433+00:00 [running]> on host 833c0b0d1c2f
[2025-08-11T02:18:29.768+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='public_health_data_pipeline' AIRFLOW_CTX_TASK_ID='stage_raw_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-08-11T02:18:28.046433+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-11T02:18:28.046433+00:00'
[2025-08-11T02:18:29.775+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-11T02:18:29.872+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-08-11T02:18:30.575+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-11T02:18:30.582+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=public_health_data_pipeline, task_id=stage_raw_data_to_s3, execution_date=20250811T021828, start_date=20250811T021829, end_date=20250811T021830
[2025-08-11T02:18:30.625+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-11T02:18:30.634+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
