[2025-08-11T20:50:12.569+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: public_health_data_pipeline.create_postgres_table_if_not_exists manual__2025-08-11T20:50:10.970479+00:00 [queued]>
[2025-08-11T20:50:12.575+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: public_health_data_pipeline.create_postgres_table_if_not_exists manual__2025-08-11T20:50:10.970479+00:00 [queued]>
[2025-08-11T20:50:12.575+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-11T20:50:12.582+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): create_postgres_table_if_not_exists> on 2025-08-11 20:50:10.970479+00:00
[2025-08-11T20:50:12.584+0000] {standard_task_runner.py:60} INFO - Started process 181 to run task
[2025-08-11T20:50:12.587+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'public_health_data_pipeline', 'create_postgres_table_if_not_exists', 'manual__2025-08-11T20:50:10.970479+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/covid_data_pipeline.py', '--cfg-path', '/tmp/tmp_ftggvl0']
[2025-08-11T20:50:12.589+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask create_postgres_table_if_not_exists
[2025-08-11T20:50:12.597+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-11T20:50:12.619+0000] {task_command.py:423} INFO - Running <TaskInstance: public_health_data_pipeline.create_postgres_table_if_not_exists manual__2025-08-11T20:50:10.970479+00:00 [running]> on host 6e6820ad3c70
[2025-08-11T20:50:12.662+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='public_health_data_pipeline' AIRFLOW_CTX_TASK_ID='create_postgres_table_if_not_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-08-11T20:50:10.970479+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-11T20:50:10.970479+00:00'
[2025-08-11T20:50:12.667+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-08-11T20:50:12.669+0000] {sql.py:450} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS covid_state_metrics (
                date DATE,
                state VARCHAR(50),
                fips INTEGER,
                cases INTEGER,
                deaths INTEGER,
                new_cases INTEGER,
                new_deaths INTEGER,
                PRIMARY KEY (date, state)
            );
        , parameters: None
[2025-08-11T20:50:12.684+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-11T20:50:12.688+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=public_health_data_pipeline, task_id=create_postgres_table_if_not_exists, execution_date=20250811T205010, start_date=20250811T205012, end_date=20250811T205012
[2025-08-11T20:50:12.727+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-11T20:50:12.737+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
